url: //banglab.com
baseurl: /banglab/

# Site settings
title: BANG LAB.
email: midaeng@gmail.com
description: "BANG's handcrafting blog "

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Mijin Baek
  pic: 1.png
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: http://facebook.com/dooly.bang
    - title: stack-overflow
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url: http://facebook.com/bybanglab
  - title: github
    url: http://github.com/midaeng

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty